# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: name-tests-test
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"] # Use config from black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        verbose: true
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--recursive=y",
            "--rcfile=pyproject.toml", # Link to your config file
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies: [types-python-dateutil]
        language: python
        "types_or": [python, pyi]
        verbose: true
        exclude: ^tests/
        args: ["--explicit-package-bases", "--config-file", "./pyproject.toml"]
