version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.10.8
    steps:
      - checkout:
          path: ~/project
      - prepare_venv: 
          run:
            name: Create venv
            command: |
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
      - prepare_tox:
          run:
            name: Runnning app tests
            command: |
              tox

workflows:
  test_my_app:
    jobs:
      - build_and_test
      