version: 2.1
orbs:
  python: circleci/python@2.0.3
  node: circleci/node@5.1.0

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install -e ".[dev]"

test: &run_pytest
  run:
    name: Pytest
    command: |
      source venv/bin/activate
      pytest -svv

style_test: &style_test
  run:
    name: Linting and Style Tests
    command: |
      source venv/bin/activate
      black app && isort app
      pylint app && mypy app

deploy: &railway_deploy
  run:
    name: Install And Deploy API To Railway
    command: |
      npm i -g @railway/cli
      railway login && railway up --detach

jobs:
  build_and_test:
    executor:
      name: python/default
      tag: "3.10" # Use Python 3.10
    steps:
      - checkout
      - *prepare_venv
      - *run_pytest
      - *style_test
  deploy:
    executor:
      name: node/default
      tag: "16.13"
    steps:
      - checkout
      - node/install
      - run: node --version
      - *railway_deploy

workflows:
  test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
