version: 2.1
orbs:
  python: circleci/python@2.0.3
  node: circleci/node@5.1.0

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install -e ".[dev]"

test: &code_test
  run:
    name: Pytest
    command: |
      pytest -svv
      black app && isort app
      pylint --recursive=y app && mypy app

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - *prepare_venv
      - *code_test

workflows:
  test_my_app:
    jobs:
      - build_and_test
