name: Deploy To Elastic BeanStalk

on:
  push:
    branches:
      - "staging"

jobs:
  build_and_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make setup_venv

      - name: Run Tests and Code Quality Checks
        run: |
          make run_checks

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: LC_API
          environment_name: Lcapi-env
          version_label: ${{ github.sha }}
          existing: elasticbeanstalk-us-east-1-126946216053
          region: us-east-1
          deployment_package: deploy.zip
